server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - name: JwtAuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: JwtAuthenticationFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: JwtAuthenticationFilter

        - id: auth-route
          uri: lb://order-service
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
