apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmart-config
data:
  POSTGRES_URL: "jdbc:postgresql://postgres-service:5432/ecommerce_db"
  KAFKA_BROKER: "kafka-service:9092"
  EUREKA_SERVER_URL: "http://discovery-service:8761/eureka/"
  ZIPKIN_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"